version: "3.8"
services:
  manifestservice:
    image: 585953033457.dkr.ecr.us-east-2.amazonaws.com/s2/cs/manifestservice:4.3.5-release-20240812
    container_name: manifest
    restart: always
    ports:
      - 8989:8989
    volumes:
    - "cs-props:/home/properties:rw"
    - "cs-server:/home/Server:rw"
    - "../logs:/home/Server/logs:rw"  
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    environment:
      SERVER_HOME: /home/Server
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: certscan
      MONGODBHOST: mongodb  
      MONGODBPORT: 27017
        #TZ: Asia/Kolkata
    networks:
      - cs_backend      
  mongo_db:
    image: "mongo:latest"
    container_name: mongodb
    volumes:
      - "mongodb:/data/db:rw"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      SERVER_HOME: /home/Server
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin 
      MONGODBHOST: mongodb
      MONGODBPORT: 27017
    restart: always
    ports:
      - 27017:27017
    networks:
      - cs_backend


volumes:
  rabbitmq:
  mongodb:
  cs-props:
    external: true
  cs-server:
    external: true
networks:
  cs_backend: